### ISSUE TITLE
missing SQL

### ISSUE THREAD

**Issue by ipwnosx** [BLIZZARD-STRESSER/xKoVx.NINJA-LEAKED#1]
wheres the sql

**Comment by Nu113d** [comment]
use any like bootme.club, kali stresser and other shits based on ghoststresser and u will need to edit db to work with this shit

**Comment by ipwnosx** [comment]
Mhmm takes time and effort I don’t have

**Comment by Nu113d** [comment]
need to add and remove from bootme.club like 3 4 rows to fix tickets and logs i think only
